#!/usr/bin/env python3
"""Generate the vocabulary table and embedded IMA-ADPCM speech assets."""

from __future__ import annotations

import argparse
import json
import shutil
import struct
import subprocess
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
WORDS_PATH = ROOT / "assets" / "music" / "vocab" / "words.json"
OUTPUT_PATH = ROOT / "main" / "vocab_data.c"
SAMPLE_RATE = 16000

STEP_TABLE = (
    7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31,
    34, 37, 41, 45, 50, 55, 60, 66, 73, 80, 88, 97, 107, 118, 130,
    143, 157, 173, 190, 209, 230, 253, 279, 307, 337, 371, 408, 449,
    494, 544, 598, 658, 724, 796, 876, 963, 1060, 1166, 1282, 1411,
    1552, 1707, 1878, 2066, 2272, 2499, 2749, 3024, 3327, 3660, 4026,
    4428, 4871, 5358, 5894, 6484, 7132, 7845, 8630, 9493, 10442,
    11487, 12635, 13899, 15289, 16818, 18500, 20350, 22385, 24623,
    27086, 29794, 32767,
)
INDEX_TABLE = (-1, -1, -1, -1, 2, 4, 6, 8, -1, -1, -1, -1, 2, 4, 6, 8)


def encode_ima(pcm: bytes) -> bytes:
    samples = struct.unpack(f"<{len(pcm) // 2}h", pcm)
    predictor = 0
    index = 0
    nibbles: list[int] = []

    for sample in samples:
        diff = sample - predictor
        sign = 8 if diff < 0 else 0
        diff = min(abs(diff), 32767)
        step = STEP_TABLE[index]
        delta = 0
        value = step >> 3
        if diff >= step:
            delta |= 4
            diff -= step
            value += step
        step >>= 1
        if diff >= step:
            delta |= 2
            diff -= step
            value += step
        step >>= 1
        if diff >= step:
            delta |= 1
            value += step

        nibble = sign | delta
        predictor += -value if sign else value
        predictor = max(-32768, min(32767, predictor))
        index = max(0, min(88, index + INDEX_TABLE[nibble]))
        nibbles.append(nibble)

    encoded = bytearray()
    for offset in range(0, len(nibbles), 2):
        high = nibbles[offset + 1] if offset + 1 < len(nibbles) else 0
        encoded.append(nibbles[offset] | (high << 4))
    return bytes(encoded)


def synthesize(entry: dict[str, str], voice: str, rate: int, work: Path) -> tuple[bytes, int]:
    say = shutil.which("say")
    ffmpeg = shutil.which("ffmpeg")
    if not say or not ffmpeg:
        raise RuntimeError("macOS say and ffmpeg are required")

    aiff = work / f"{entry['word']}.aiff"
    raw = work / f"{entry['word']}.pcm"
    text = f"{entry['word']}. {entry['example']}"
    subprocess.run([say, "-v", voice, "-r", str(rate), "-o", str(aiff), text], check=True)
    subprocess.run(
        [
            ffmpeg, "-loglevel", "error", "-y", "-i", str(aiff),
            "-af", "loudnorm=I=-18:TP=-2:LRA=7",
            "-ar", str(SAMPLE_RATE), "-ac", "1", "-f", "s16le", str(raw),
        ],
        check=True,
    )
    pcm = raw.read_bytes()
    return encode_ima(pcm), len(pcm) // 2


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render(entries: list[dict[str, str]], clips: list[tuple[bytes, int]], voice: str) -> str:
    lines = [
        '#include "vocab_data.h"',
        "",
        f"// Generated by tools/generate_vocab_audio.py with the macOS {voice} voice.",
    ]
    for index, (encoded, _) in enumerate(clips):
        lines.append(f"static const uint8_t AUDIO_{index}[] = {{")
        for offset in range(0, len(encoded), 16):
            chunk = ", ".join(f"0x{byte:02x}" for byte in encoded[offset:offset + 16])
            lines.append(f"    {chunk},")
        lines.append("};")
        lines.append("")

    lines.append("const vocab_item_t VOCAB_ITEMS[VOCAB_ITEM_COUNT] = {")
    for index, (entry, (encoded, sample_count)) in enumerate(zip(entries, clips)):
        lines.extend(
            [
                "    {",
                f"        .word = {c_string(entry['word'])},",
                f"        .meaning = {c_string(entry['meaning'])},",
                f"        .example = {c_string(entry['example'])},",
                f"        .audio = AUDIO_{index},",
                f"        .audio_bytes = {len(encoded)},",
                f"        .sample_count = {sample_count},",
                "    },",
            ]
        )
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--voice", default="Samantha")
    parser.add_argument("--rate", type=int, default=155)
    args = parser.parse_args()

    entries = json.loads(WORDS_PATH.read_text(encoding="utf-8"))
    if len(entries) != 10:
        raise RuntimeError("words.json must contain exactly 10 entries")

    with tempfile.TemporaryDirectory(prefix="ai-passport-vocab-") as temp:
        work = Path(temp)
        clips = [synthesize(entry, args.voice, args.rate, work) for entry in entries]

    OUTPUT_PATH.write_text(render(entries, clips, args.voice), encoding="utf-8")
    total_bytes = sum(len(encoded) for encoded, _ in clips)
    total_seconds = sum(samples for _, samples in clips) / SAMPLE_RATE
    print(f"Generated {len(clips)} clips, {total_seconds:.1f}s, {total_bytes / 1024:.1f} KiB ADPCM")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
